name: TS-Playlist
on:
 workflow_dispatch:
  inputs:
    git_token:
      description: 'Enter your GitHub Token'     
      required: true
    tata_mobile:
      description: 'Enter your Tata Sky Mobile Number'
      required: true
    sub_id:
      description: 'Enter your Tata Sky Subscriber ID'
      required: true
    tata_pass:
      description: 'Enter your Tata Sky Password'     
      required: true
    git_mail:
      description: 'Enter your GitHub Mail Address'
      required: true
    git_id:
      description: 'Enter your GitHub ID'
      required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
    - name: Installing Dependencies
      continue-on-error: true
      run: |
            git config --global user.name "${{ github.event.inputs.git_id }}"
            git config --global user.email "${{ github.event.inputs.git_mail }}"
            git clone https://github.com/Sanju2015/Tata-Sky-IPTV
            cd Tata-Sky-IPTV/
            cd code_samples/
            sudo apt install expect -y
            wget https://gist.githubusercontent.com/chammii1978/986cf8a69e0db43eec88c510b1017dcf/raw/TSlogin.exp
            chmod 777 TSlogin.exp
            sed -i 's/PASSWORD/${{ github.event.inputs.tata_pass }}/g' TSlogin.exp
            sed -i 's/SUB_ID/${{ github.event.inputs.sub_id }}/g' TSlogin.exp
            sed -i 's/MOB_NO/${{ github.event.inputs.tata_mobile }}/g' TSlogin.exp
            ./TSlogin.exp >> /dev/null 2>&1
            touch mytoken.txt
            echo "${{ github.event.inputs.git_token }}" >> mytoken.txt
            gh auth login --with-token < mytoken.txt
            mkdir git-repo/
            cd git-repo/
            touch mytatasky.m3u
            echo "Initial Test" >> mytatasky.m3u
            gh gist create mytatasky.m3u | tee gist_link.txt
            sed -i 's/gist/${{ github.event.inputs.git_token }}@gist/g' gist_link.txt
            gist_url=$(cat gist_link.txt)
            dir="${gist_url##*/}"
            git clone https://github.com/Sanju2105/Tata-Sky-IPTV
            gh repo create MyTataSky-Daily --private -y || echo "New repo has been created"
            mv ../TSlogin.exp Tata-Sky-IPTV/code_samples/
            chmod 755 Tata-Sky-IPTV/code_samples/TSlogin.exp
            cd Tata-Sky-IPTV/
            mkdir .github
            cd .github
            mkdir workflows
            cd workflows
            wget https://gist.githubusercontent.com/chammii1978/b2432a6b5c5eaedd87f9d250d725fc7d/raw/TSDailyWF.yml
            wget https://gist.githubusercontent.com/chammii1978/f4dc692245015dbc272d89a854fe6c90/raw/TSaddon.txt
            export dir=$dir
            export gist_url=$gist_url
            export git_id=${{ github.event.inputs.git_id }}
            export git_token=${{ github.event.inputs.git_token }}
            export git_mail=${{ github.event.inputs.git_mail }}
            cat TSaddon.txt | envsubst >> TSDailyWF.yml
            rm TSaddon.txt
            cd ../..
            rm -rf .git
            cd ..
            git clone https://${{ github.event.inputs.git_token }}@github.com/${{ github.event.inputs.git_id }}/MyTataSky-Daily
            rm -rf MyTataSky-Daily/*
            rm -rf MyTataSky-Daily/.github
            mv Tata-Sky-IPTV/* MyTataSky-Daily/
            mv Tata-Sky-IPTV/.github MyTataSky-Daily/
            cd MyTataSky-Daily/
            git add .
            git commit --author="chammii<chammii.bdn@gmail.com>" -m "Update Repo"
            git push
